steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull "${_CACHE_IMAGE}" || true

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --target
      - ${_TARGET}
      - --build-arg
      - SOURCE_COMMIT=${_SOURCE_COMMIT}
      - --cache-from
      - ${_CACHE_IMAGE}
      - --build-arg
      - APP_BASE_PATH=${_APP_BASE_PATH}
      - --build-arg
      - VITE_APP_MODE=${_VITE_APP_MODE}
      - --build-arg
      - VITE_CAN_REVIEW_NODES=${_VITE_CAN_REVIEW_NODES}
      - -t
      - ${_IMAGE}
      - -t
      - ${_CACHE_IMAGE}
      - .

  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - if [ "${_PUSH_CACHE_IMAGE}" = "true" ] && [ "${_CACHE_IMAGE}" != "${_IMAGE}" ]; then docker push "${_CACHE_IMAGE}"; fi

images:
  - ${_IMAGE}

serviceAccount: projects/chm-network/serviceAccounts/explorer-build-sa@chm-network.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TARGET: web
  _SOURCE_COMMIT: unknown
  _APP_BASE_PATH: /explorer
  _VITE_APP_MODE: author
  _VITE_CAN_REVIEW_NODES: "true"
  _IMAGE: us-east4-docker.pkg.dev/chm-network/chm-apps/explorer:latest
  _CACHE_IMAGE: us-east4-docker.pkg.dev/chm-network/chm-apps/explorer:latest
  _PUSH_CACHE_IMAGE: "true"
